# Generated by Django 3.2.8 on 2021-11-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('First', '0016_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(max_length=700),
        ),
    ]
