# Generated by Django 3.2.8 on 2021-11-12 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('First', '0017_alter_comment_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created',)},
        ),
    ]
