# Generated by Django 3.2.8 on 2021-11-13 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('First', '0018_alter_comment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='Flight_Distination',
            field=models.CharField(choices=[('tehran', 'tehran'), ('abadan', 'abadan'), ('mashhadddd', "mash'had"), ('shiraz', 'shiraz'), ('isfahan', 'isfahan'), ('chabahar', 'chabahar')], max_length=30),
        ),
        migrations.AlterField(
            model_name='flight',
            name='Flight_Origin',
            field=models.CharField(choices=[('tehran', 'tehran'), ('abadan', 'abadan'), ('mashhadddd', "mash'had"), ('shiraz', 'shiraz'), ('isfahan', 'isfahan'), ('chabahar', 'chabahar')], max_length=30),
        ),
        migrations.CreateModel(
            name='supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('Flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fsupplier', to='First.flight')),
            ],
        ),
    ]
